export const products = [
  {
    id: 'iphone-17-air',
    name: 'iPhone 17 Air',
    category: 'iPhone',
    summary: 'Diseño más delgado, gran pantalla y una experiencia pensada para ligereza y autonomía.',
    price: 'Desde $899',
    accent: 'from-sky-400/30 to-cyan-300/10',
  },
  {
    id: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    category: 'iPhone',
    summary: 'Cámara profesional, mejor rendimiento y nuevas funciones para creación de contenido.',
    price: 'Desde $1,099',
    accent: 'from-indigo-400/25 to-violet-300/10',
  },
  {
    id: 'iphone-17-pro-max',
    name: 'iPhone 17 Pro Max',
    category: 'iPhone',
    summary: 'La versión más completa de la línea, con pantalla más grande y batería de larga duración.',
    price: 'Desde $1,299',
    accent: 'from-fuchsia-400/25 to-pink-300/10',
  },
  {
    id: 'mac-neo',
    name: 'Mac Neo',
    category: 'Mac',
    summary: 'Una Mac pensada para equilibrio entre potencia, eficiencia y trabajo diario.',
    price: 'Desde $1,499',
    accent: 'from-slate-200/20 to-white/5',
  },
  {
    id: 'macbook-pro-m5',
    name: 'MacBook Pro M5',
    category: 'Mac',
    summary: 'Rendimiento de nueva generación para edición, desarrollo y tareas creativas exigentes.',
    price: 'Desde $2,199',
    accent: 'from-zinc-300/20 to-white/5',
  },
  {
    id: 'apple-watch-series-11',
    name: 'Apple Watch Series 11',
    category: 'Watch',
    summary: 'Seguimiento de salud, actividad y métricas diarias con un diseño más refinado.',
    price: 'Desde $429',
    accent: 'from-emerald-400/25 to-teal-300/10',
  },
  {
    id: 'airpods-pro-3',
    name: 'AirPods Pro 3',
    category: 'Audio',
    summary: 'Audio espacial, mejor cancelación de ruido y batería optimizada para el día a día.',
    price: 'Desde $279',
    accent: 'from-amber-400/25 to-orange-300/10',
  },
  {
    id: 'airpods-max-2',
    name: 'AirPods Max 2',
    category: 'Audio',
    summary: 'Sonido envolvente premium, diseño de diadema y cancelación de ruido de nivel alto.',
    price: 'Desde $549',
    accent: 'from-violet-400/25 to-fuchsia-300/10',
  },
]
